---
name: "Cloudflared"
version: "1.0.0"
slug: "cloudflared"
description: "Expose your Home Assistant instance to the internet using Cloudflare Tunnel"
url: "https://github.com/kerbart/addon-cloudflared"
codenotary: dev@brenner.tech
init: false
stage: stable
startup: services
boot: auto
homeassistant: "2023.1.0"
hassio_api: true
hassio_role: homeassistant
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
options:
  external_hostname: ""
  additional_hosts: []
ports:
  36500/tcp: null
schema:
  external_hostname: str?
  additional_hosts:
    - hostname: str
      service: str
      disableChunkedEncoding: bool?
  tunnel_name: str?
  catch_all_service: str?
  nginx_proxy_manager: bool?
  use_builtin_proxy: bool?
  tunnel_token: str?
  post_quantum: bool?
  run_parameters:
    - match(^(--edge-bind-address|--edge-ip-version|--grace-period|--ha-connections|--logfile|--loglevel|--pidfile|--protocol|--region|--retries|--tag)=.*$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
